# Generated by Django 4.1.7 on 2023-05-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=32)),
                ('lastname', models.CharField(max_length=32)),
                ('phonenumber', models.CharField(max_length=10)),
                ('password', models.CharField(default='password', max_length=32)),
                ('account_type', models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], max_length=7)),
                ('user_appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_for_users', to='my_models.appointment')),
            ],
            options={
                'db_table': 'jinsei_user',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor_appointments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments_for_doctors', to='my_models.appointment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_models.appuser')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_models.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_models.appuser'),
        ),
    ]
