# Generated by Django 4.1.7 on 2023-05-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='account_type',
            new_name='accounttype',
        ),
    ]
