# Generated by Django 4.1.7 on 2023-05-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0005_remove_appuser_accounttype_remove_doctor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
