# Generated by Django 4.1.7 on 2023-05-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0006_doctor_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='start_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
