# Generated by Django 4.1.7 on 2023-05-12 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0008_alter_doctor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name should only contain letters and be between 2 and 32 characters.', regex='^[a-zA-Z]{2,32}$')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name should only contain letters and be between 2 and 32 characters.', regex='^[a-zA-Z]{2,32}$')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password should be between 8 and 32 characters', regex='^.{8,32}$')]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phonenumber',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone should only contain numbers and should be 10 characters', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name should only contain letters and be between 2 and 32 characters.', regex='^[a-zA-Z]{2,32}$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name should only contain letters and be between 2 and 32 characters.', regex='^[a-zA-Z]{2,32}$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password should be between 8 and 32 characters', regex='^.{8,32}$')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password should be between 8 and 32 characters', regex='^.{8,32}$')]),
        ),
    ]
