# Generated by Django 4.1.7 on 2023-06-01 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0014_appointment_content_type_appointment_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
    ]
