# Generated by Django 4.1.7 on 2023-06-03 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0016_appointment_patientphonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patientphonenumber',
        ),
    ]
