# Generated by Django 4.1.7 on 2023-06-04 11:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0019_appuser_sex_doctor_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=0, max_digits=3), size=None)),
                ('oxygen_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medication', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
