# Generated by Django 4.1.7 on 2023-06-05 01:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0025_delete_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pulse_rate', models.IntegerField()),
                ('blood_pressure', models.JSONField(blank=True, null=True)),
                ('oxygen_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medication', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_models.appointment')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
