# Generated by Django 4.1.7 on 2023-06-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0028_rename_bp_prescription_bloodpressure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='bloodpressure',
            new_name='blood_pressure',
        ),
    ]
