# Generated by Django 4.1.7 on 2023-06-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0031_alter_prescription_blood_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
