# Generated by Django 4.1.7 on 2023-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0032_prescription_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
