# Generated by Django 4.1.7 on 2023-06-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0033_alter_prescription_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='creation_date',
            new_name='date',
        ),
    ]
