# Generated by Django 4.1.7 on 2023-06-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0035_rename_date_prescription_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='createddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
