# Generated by Django 4.1.7 on 2023-09-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0037_appuser_mealschedule_doctor_mealschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='mealschedule',
            field=models.JSONField(default=dict),
        ),
    ]
