# Generated by Django 4.1.7 on 2023-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0038_alter_appuser_mealschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bloodgroup',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=4, null=True),
        ),
    ]
